---
title: "Histogram_comparison"
author: "ST"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Code for histogram comparison. 
Copy and paste into master code. 

```{r}
library(ggplot2) 

# List of timepoint data frames containing D
list_timepoint_calc <- c('timepoint_01_calculations', 'timepoint_02_calculations', 'timepoint_03_calculations', 'timepoint_04_calculations', 'timepoint_05_calculations', 'timepoint_06_calculations', 'timepoint_07_calculations', 'timepoint_08_calculations', 'timepoint_09_calculations', 'timepoint_10_calculations', 'timepoint_11_calculations', 'timepoint_12_calculations', 'timepoint_13_calculations', 'timepoint_14_calculations', 'timepoint_15_calculations', 'timepoint_16_calculations', 'timepoint_17_calculations', 'timepoint_18_calculations')


# Empty list for plots
list_hist <- list()

# Iterate through list_timepoint_calc and generate plots
for (x in 1:length(list_timepoint_calc)){
  time <- timepoint_dictionary[as.numeric(gsub("\\D", "", list_timepoint_calc[x]))]

  # Generate histogram title
  title <- paste("LexA Movement After Antibiotic Treatment, t =", time, "min \n")
  
  #Get data frame
  df <- (get(list_timepoint_calc[x]))
  
  # Plot histogram
  hist <- ggplot(df, aes(x=D)) + geom_histogram(binwidth = 1, aes(y=..count../sum(..count..))) + 
    ylim(0,.25) + 
    labs(x = bquote('Diffusion Coefficient (D)' ~ (μm^2/s)), y = "Normalised Frequency", title = title) + 
    theme_minimal()
  
  # Store histogram in list_hist
  list_hist[[length(list_hist) + 1]] <- hist
}

# Show all plots
for (plot in list_hist) {
  print(plot)
}
```